### ISSUE TITLE
Validator cli is not working with ledger wallet

### ISSUE THREAD

**Issue by badrogger** [skalenetwork/validator-cli#379]
Validator cli Linux build cannot sign transaction with ledger wallet because of recent rlp.encode changes. 
```
2024-10-22 12:23:42,237 - utils.helper - ERROR - Did not find sedes handling type TypedTransaction
Traceback (most recent call last):
  File "cli/main.py", line 119, in <module>
    cmd_collection()
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "utils/helper.py", line 166, in wrapper
    return func(*args, fee=fee, **kwargs)
  File "cli/validator.py", line 86, in _register
    register(
  File "core/validator.py", line 46, in register
    tx_res = skale.validator_service.register_validator(
  File "skale/contracts/base_contract.py", line 107, in wrapper
  File "skale/wallets/ledger_wallet.py", line 175, in sign_and_send
  File "skale/wallets/ledger_wallet.py", line 165, in sign
  File "skale/wallets/ledger_wallet.py", line 122, in make_payload
  File "rlp/codec.py", line 120, in encode
  File "rlp/codec.py", line 318, in infer_sedes
TypeError: Did not find sedes handling type TypedTransaction
```

**Comment by PolinaKiporenko** [comment]
1.3.3 version validator cli not work properly with ledger
